services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: orignym
      POSTGRES_PASSWORD: orignym_password
      POSTGRES_DB: orignym
    ports:
      - "35521:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      network: host
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://orignym:orignym_password@db:5432/orignym?schema=public
      - NEXTAUTH_SECRET=fallback_secret_for_local_prod
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      - db

volumes:
  pgdata: